#FROM debian:stretch-slim
FROM mcr.microsoft.com/dotnet/sdk:6.0

ARG BUNDLE_DIR

RUN apt-get update && apt-get install -y ca-certificates
RUN apt install unzip

# This is a template Dockerfile for the bundle's invocation image
# You can customize it to use different base images, install tools and copy configuration files.
#
# Porter will use it as a template and append lines to it for the mixins
# and to set the CMD appropriately for the CNAB specification.
#
# Add the following line to porter.yaml to instruct Porter to use this template
# dockerfile: Dockerfile.tmpl

# You can control where the mixin's Dockerfile lines are inserted into this file by moving "# PORTER_MIXINS" line
# another location in this file. If you remove that line, the mixins generated content is appended to this file.
# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle

COPY . $BUNDLE_DIR
#TODO: Not sure why this was not working until I did after COPY above. Investigate this further
RUN curl -L https://www.nuget.org/api/v2/package/Microsoft.PowerApps.CLI.Core.linux-x64/1.21.13 --output /cnab/app/pac.nuget
RUN cd /cnab/app/ && unzip /cnab/app/pac.nuget && chmod +x /cnab/app/tools/pac
RUN pwsh --File /cnab/app//scripts/prerequisites.ps1


